SELECT NOW(), CURDATE(), CURTIME();

SELECT YEAR(NOW());

SELECT MONTH(NOW());

SELECT DAY(NOW());

SELECT HOUR(NOW());

SELECT MINUTE(NOW());

SELECT DAYNAME(NOW());

SELECT MONTHNAME(NOW());

SELECT EXTRACT(DAY FROM NOW());

SELECT EXTRACT(YEAR FROM NOW());

SELECT * FROM orders WHERE order_date >= '2019-01-01';

SELECT * FROM orders WHERE YEAR(order_date) = YEAR(NOW());

SELECT DATE_FORMAT(NOW(), '%M %d %Y');

SELECT TIME_FORMAT(NOW(), '%H:%i %p');

SELECT DATE_ADD(NOW(), INTERVAL 1 DAY);

SELECT DATE_ADD(NOW(), INTERVAL -1 DAY);

SELECT DATE_ADD(NOW(), INTERVAL 1 YEAR);

SELECT DATE_SUB(NOW(), INTERVAL 1 YEAR);

SELECT DATEDIFF('2019-01-05 09:00', '2019-01-01 17:00');

SELECT TIME_TO_SEC('09:00') - TIME_TO_SEC('09:02');